### ISSUE TITLE
seg fault core dumped

### ISSUE THREAD

**Issue by AurelBec** [tejus-gupta/hybrid-astar-planner#1]
you should replace 
```if (nearest_obstacle[i][j] == 0 && i >= 0 && i < MAPX && j >= 0 && j < MAPY && obs_map[i][j] == 0) {...}```
in void Map::find_near_obs() in src/Map.cpp by 
```if (i >= 0 && i < MAPX && j >= 0 && j < MAPY) { if (nearest_obstacle[i][j] == 0 && obs_map[i][j] == 0) {...} }```
to avoid some errors.

**Comment by tejus-gupta** [comment]
Thanks for pointing out the issue!

The code here is outdated. I will try to push the latest code with ROS integration and vehicle control by this week.

**Comment by AurelBec** [comment]
Nice! I'll stay up to date then! :D
